[package]
name = "ebina-webhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
dotenv = "0.15"
futures = "0.3.17"
hmac = "0.11.0"
sha2 = "0.9.8"
