name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --workspace -- -D warnings

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: Swatinem/rust-cache@v1
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --workspace --verbose --release -- -D warnings

  release:
    if: (github.head_ref == 'knope/release' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: knope-dev/knope-version@v1
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v1
      - run: knope release

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
              -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          data: "{ 'data': 'data' }"
