name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Swatinem/rust-cache@v1
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ebina
        path: |
          target/release/ebina-bot
          target/release/ebina-webhook
  release:
    needs: build
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Download binary files
        uses: actions/download-artifact@v2
        with:
          name: ebina
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ebina